# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=35)),
                ('complemento', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=25)),
                ('Estado', models.CharField(max_length=2)),
                ('Cep', models.CharField(max_length=8)),
                ('foneResidencial', models.CharField(max_length=15)),
                ('foneTrabalho', models.CharField(max_length=15)),
                ('rendaFamiliar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=38)),
                ('endereco', models.CharField(max_length=35)),
                ('complemento', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=25)),
                ('Estado', models.CharField(max_length=2)),
                ('Cep', models.CharField(max_length=14)),
                ('fone', models.CharField(max_length=15)),
                ('responsavel', models.CharField(max_length=15)),
                ('website', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPedido', models.DateTimeField()),
                ('dataRecebimento', models.DateTimeField()),
                ('precoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codFornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=38)),
                ('quantidade', models.IntegerField()),
                ('minQuantidade', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataVenda', models.DateTimeField()),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='codProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='codVenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Venda'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='codPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pedido'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='codProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
    ]
