# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170419_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='website',
            field=models.CharField(max_length=80),
        ),
    ]
